import itertools
import random

# ===== 1. SEED ENGLISH HEAD TERMS =====
head_terms_en = [
    "motorcycle accident lawyer",
    "car accident lawyer",
    "truck accident attorney",
    "personal injury lawyer",
    "business lawyer",
    "tax attorney",
    "online degree program",
    "mba online",
    "data science course",
    "cybersecurity certification",
    "cloud computing course",
    "docker kubernetes training",
    "python programming course",
    "seo agency",
    "google ads management",
    "facebook ads agency",
    "tiktok ads service",
    "email marketing software",
    "marketing automation tool",
    "crm software",
    "saas platform",
    "project management software",
    "time tracking software",
    "invoice software",
    "accounting software",
    "erpsystem for small business",
    "warehouse management software",
    "inventory management system",
    "vpn service",
    "password manager",
    "antivirus software",
    "web hosting",
    "vps hosting",
    "cloud hosting",
    "wordpress hosting",
    "landing page builder",
    "website builder",
    "shopify development service",
    "woocommerce development",
    "magento development",
    "dropshipping supplier",
    "affiliate marketing program",
    "forex trading platform",
    "crypto trading exchange",
    "stock trading app",
    "credit repair service",
    "debt consolidation loan",
    "personal loan online",
    "mortgage refinance",
    "student loan refinance",
    "health insurance plan",
    "life insurance quote",
    "travel insurance plan",
    "pet insurance plan",
    "home security system",
    "smart home automation",
    "solar panel installation",
    "roof repair service",
    "emergency plumbing service",
    "hvac repair service",
    "pest control service",
    "car detailing service",
    "mobile mechanic",
    "hair transplant clinic",
    "cosmetic surgery clinic",
    "dental implant clinic",
    "teeth whitening service",
    "online therapy",
    "mental health counseling",
    "drug rehab center",
    "alcohol rehab center",
    "yoga retreat",
    "meditation retreat",
    "travel tour package",
    "cheap flight tickets",
    "hotel booking site",
    "vacation rental platform",
    "freelance marketplace",
    "online job board",
    "cv resume writer",
    "career coaching",
    "online english course",
    "ielts online course",
    "toeic preparation course",
    "kids english app",
    "coding bootcamp",
    "web development bootcamp",
    "mobile app development course",
    "ai content writer",
    "text to speech tool",
    "voice over service",
    "video editing service",
    "youtube channel manager",
    "podcast editing service",
    "influencer marketing agency"
]

# ===== 2. SEED VIETNAMESE HEAD TERMS (KHÔNG DẤU) =====
head_terms_vi = [
    "luat su tai nan giao thong",
    "luat su tai nan lao dong",
    "luat su tranh chap hop dong",
    "luat su doanh nghiep nho",
    "tu van thue doanh nghiep",
    "dich vu ke toan tron goi",
    "dich vu thanh lap cong ty",
    "dich vu giai the doanh nghiep",
    "khoa hoc marketing online",
    "khoa hoc seo tong the",
    "khoa hoc google ads",
    "khoa hoc tiktok ads",
    "khoa hoc facebook marketing",
    "khoa hoc lap trinh python",
    "khoa hoc lap trinh web",
    "khoa hoc data science",
    "khoa hoc tri tue nhan tao",
    "khoa hoc ux ui online",
    "khoa hoc kinh doanh online",
    "khoa hoc ban hang livestream",
    "khoa hoc content marketing",
    "khoa hoc edit video",
    "khoa hoc quay dung youtube",
    "khoa hoc kiem tien online",
    "hoc tieng anh giao tiep",
    "hoc tieng anh cho nguoi mat goc",
    "khoa hoc ielts online",
    "luyen thi toeic online",
    "ung dung hoc tieng anh cho tre em",
    "khoa hoc kinh doanh bat dong san",
    "khoa hoc dau tu chung khoan",
    "khoa hoc forex co ban",
    "khoa hoc dau tu crypto",
    "khoa hoc quan ly tai chinh ca nhan",
    "bao hiem nhan tho gia dinh",
    "bao hiem suc khoe gia dinh",
    "bao hiem du lich quoc te",
    "bao hiem o to truc tuyen",
    "bao hiem xe may gia re",
    "vay tin chap tieu dung",
    "vay mua nha tra gop",
    "vay mua xe o to",
    "vay von kinh doanh nho",
    "phan mem quan ly ban hang",
    "phan mem quan ly kho",
    "phan mem quan ly nhan su",
    "phan mem cham cong tinh luong",
    "phan mem quan ly spa",
    "phan mem quan ly phong kham",
    "phan mem quan ly nha thuoc",
    "dich vu seo tong the",
    "dich vu chay quang cao google",
    "dich vu chay quang cao facebook",
    "dich vu chay quang cao tiktok",
    "dich vu viet content chuan seo",
    "thiet ke website wordpress",
    "thiet ke landing page",
    "thiet ke logo thuong hieu",
    "dich vu quay dung video doanh nghiep",
    "dich vu chup anh san pham",
    "dich vu livestream ban hang",
    "dich vu quan ly fanpage",
    "dich vu quan ly tiktok shop",
    "dich vu mo gian hang shopee",
    "dich vu mo gian hang lazada",
    "dich vu mo gian hang tiki",
    "khoa hoc ban hang shopee",
    "khoa hoc ban hang tiktok shop",
    "khoa hoc ban hang facebook",
    "khoa hoc ban hang zalo",
    "dich vu ve sinh cong nghiep",
    "dich vu ve sinh van phong",
    "dich vu ve sinh nha o",
    "dich vu giat u cong nghiep",
    "dich vu cham soc o to",
    "dich vu rua xe tai nha",
    "dich vu don nha theo gio",
    "dich vu giup viec theo gio",
    "dich vu cham soc nguoi cao tuoi",
    "dich vu cham soc sau sinh",
    "spa cham soc da mat",
    "spa tri mun chuyen sau",
    "spa tri tham nam tan nhang",
    "spa tri seo ro",
    "dich vu phun xam tham my",
    "nha khoa rang su tham my",
    "nha khoa trong rang implant",
    "nha khoa nieng rang trong suot",
    "phong kham da khoa uy tin",
    "phong kham nhi uy tin",
    "phong kham phu san",
    "phong kham da lieu",
    "tour du lich phu quoc",
    "tour du lich da lat",
    "tour du lich da nang",
    "tour du lich nha trang",
    "tour du lich ha giang",
    "tour du lich sapa",
    "khach san gia re ha noi",
    "khach san gia re da nang",
    "khach san gan bien phu quoc",
    "homestay view dep da lat",
    "villa nghi duong gia dinh",
    "xe dua don san bay",
    "cho thue xe tu lai",
    "cho thue xe co tai xe",
    "khoa hoc lai xe o to",
    "trung tam luyen thi bang lai xe"
]

# ===== 3. MODIFIERS CHUNG (EN + VI KHÔNG DẤU) =====
modifiers = [
    "near me",
    "online",
    "uy tin",
    "gia re",
    "chuyen nghiep",
    "chat luong cao",
    "tot nhat",
    "cho nguoi moi",
    "cap toc",
    "tai ha noi",
    "tai ho chi minh",
    "tai tphcm",
    "tai da nang",
    "tai can tho",
    "tai hai phong",
    "tai viet nam",
    "review",
    "2024",
    "2025",
    "mien phi",
    "tra gop",
    "khong can the chap",
    "luong cao",
    "lam tai nha",
    "full time",
    "part time",
    "remote",
    "on site",
    "hop dong dai han",
    "ngan han",
    "danh gia cao",
    "cho doanh nghiep nho",
    "cho startup",
    "cho hoc sinh",
    "cho sinh vien",
    "cho nguoi di lam",
    "cho nguoi mat goc",
    "cho tre em",
    "cao cap",
    "gia tot",
    "tiet kiem chi phi",
    "gan toi",
    "gan trung tam",
    "ho tro 24 7",
    "tu van mien phi",
    "bao hanh dai han",
    "tinh phi theo gio",
    "trai nghiem mien phi"
]

def build_keywords():
    keywords = set()

    # EN head + modifier
    for h, m in itertools.product(head_terms_en, modifiers):
        keywords.add(f"{h} {m}")

    # VI head + modifier
    for h, m in itertools.product(head_terms_vi, modifiers):
        keywords.add(f"{h} {m}")

    # Một số pattern bổ sung cho đa dạng
    extra_patterns = [
        "huong dan {h}",
        "khoa hoc {h} online",
        "bi quyet {h}",
        "kinh nghiem {h}",
        "cam nang {h}",
        "review {h}",
        "so sanh {h}",
        "gia {h}",
        "{h} la gi",
        "nen chon {h} hay khong",
    ]

    for h in head_terms_vi:
        base = h
        for tmpl in extra_patterns:
            keywords.add(tmpl.format(h=base))

    # Đảm bảo có ít nhất 5000 keyword, nếu dư thì cắt bớt
    keywords_list = list(keywords)
    random.shuffle(keywords_list)
    if len(keywords_list) < 5000:
        print(f"Warning: only generated {len(keywords_list)} keywords, consider adding more seeds.")
    return keywords_list[:5000]

def save_to_file(filename="keywords_5000.txt"):
    kws = build_keywords()
    with open(filename, "w", encoding="utf-8") as f:
        for kw in kws:
            f.write(kw + "\n")
    print(f"Saved {len(kws)} keywords to {filename}")

if __name__ == "__main__":
    save_to_file()
